#ifndef MARKDOWNEDITVIEW_GLOBAL_H
#define MARKDOWNEDITVIEW_GLOBAL_H

#if defined(MARKDOWNEDITVIEW_LIBRARY)
#  define MARKDOWNEDITVIEW_EXPORT Q_DECL_EXPORT
#else
#  define MARKDOWNEDITVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // MARKDOWNEDITVIEW_GLOBAL_H
